baseURL = "https://sagrouptalentmanagement.in/"
languageCode = "en-in"
title = "S A Group Talent Management"
paginate = 5
paginatePath = "page"
[taxonomies]
  category = "categories"
  tag = "tags"
  location = "locations"
  qualification = "qualifications"
[params]
	description = "Make your carrier bloom with us"
	logo = "https://sagrouptalentmanagement.weebly.com/uploads/4/5/7/1/45714543/logo-2.jpg"
	coverImage = "https://i.postimg.cc/fTFK9VKh/minh-pham-Iis-DPFNUS4k-unsplash.jpg"
	address = "Plot No-2, Near Bharat Gas Agency, Hapur - Modinagar Rd, Shastri Nagar, Modinagar, India-201204"
	postJobForm = "https://cutt.ly/8yEpWcG"
	[params.social]
		messenger = "https://m.me/sagrouptalentmanagement/"
		facebook = "https://www.facebook.com/sagrouptalentmanagement/"
		whatsapp = "https://wa.me/917906094184/?text=Hi,%20I%20found%20this%20from%20website"
		email = "info@sagrouptalentmanagement.in"
		googleplay = "http://bit.ly/2VpJOgm"
	[params.mailing]
		url = "https://docs.google.com/forms/d/e/1FAIpQLSdGE1JesFuZJwliqzKz4DjvAtZMgOhMYw7fRDSqylPX7omORg/formResponse"
		name = "entry.1196241558"
	[params.theme]
		opaque = "#3f51b5"
		translucent = "#3f51b54d"
	[[params.clients]]
		title = "ICCS BPO LTD"
		image = "https://sagrouptalentmanagement.weebly.com/uploads/4/5/7/1/45714543/iccs-ltd_orig.png"
	[[params.clients]]
		title = "TECH INDIA SOLUTION PVT LTD"
		image = "https://sagrouptalentmanagement.weebly.com/uploads/4/5/7/1/45714543/tech-india-solution_orig.jpg"
	[[params.clients]]
		title = "KARVY DIGIKONNECT"
		image = "https://sagrouptalentmanagement.weebly.com/uploads/4/5/7/1/45714543/karvy_orig.png"
	[[params.clients]]
		title = "Easy Policy"
		image = "https://i.postimg.cc/0286720k/SAHFF-Nv-400x400.png"
