baseURL = "https://sagrouptalentmanagement.in/"
languageCode = "en-in"
title = "S A Group Talent Management"
paginate = 5
paginatePath = "jobs"
[taxonomies]
  category = "categories"
  tag = "tags"
  location = "locations"
  qualification = "qualifications"
[params]
	description = "::  Make you Carrier with us  ::"
	logo = "https://sagrouptalentmanagement.weebly.com/uploads/4/5/7/1/45714543/logo-2.jpg"
	themeColor = "#3f51b5"
	coverImage = "https://i.postimg.cc/fTFK9VKh/minh-pham-Iis-DPFNUS4k-unsplash.jpg"
	messenger = "https://m.me/sagrouptalentmanagement/"
	facebook = "https://www.facebook.com/sagrouptalentmanagement/"
	whatsapp = "https://wa.me/917906094184/?text=Hi,%20I%20found%20this%20from%20website"
	email = "S.A.Group.Talent.Management@gmail.com"
	googleplay = "http://bit.ly/2VpJOgm"
	address = "Plot No-2, Near Bharat Gas Agency, Hapur - Modinagar Rd, Shastri Nagar, Modinagar, India-201204"
	postJobForm = "https://cutt.ly/8yEpWcG"
	mailinglist = "https://docs.google.com/forms/d/e/1FAIpQLSdGE1JesFuZJwliqzKz4DjvAtZMgOhMYw7fRDSqylPX7omORg/formResponse?usp=pp_url&entry.1196241558=sumitkarn123@gmail.com"
