baseURL = "http://example.org/"
languageCode = "en-in"
title = "Jobkaro"
paginate = 5
paginatePath = "jobs"
[taxonomies]
  category = "categories"
  tag = "tags"
  location = "locations"
  qualification = "qualifications"